name: Deploy VuePress site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List dist directory after build
        run: ls -la ./dist

      - name: Check if dist directory exists
        run: |
          if [ -d "./dist" ]; then
            echo "dist directory exists."
          else
            echo "dist directory does NOT exist."
            exit 1
          fi

      - name: Deploy to GitHub Pages
        if: github.repository == 'biantailab/chem-game'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
